// vendorVisitStoreProducts.js
export const vendorProducts = [
  {
    id: 1,
    name: "Premium Spare Parts",
    description: "Active noise cancellation",
    price: 103.99,
    originalPrice: 129.99,
    stock: 24,
    category: "Body-Parts",
    rating: 4.8,
    image: "",
    badge: { text: "20% OFF", type: "discount", color: "red" },
  },
  {
    id: 2,
    name: "Smart Wheel",
    description: "Health tracking, waterproof, OLED display",
    price: 89.99,
    stock: 15,
    category: "Wheels & Rims",
    rating: 4.6,
    image: "",
    badge: { text: "NEW", type: "new", color: "green" },
  },
  {
    id: 3,
    name: "Power Parts",
    description: "Fast charging",
    price: 29.99,
    stock: 32,
    category: "Air Filter",
    rating: 4.5,
    image: "",
  },
  {
    id: 4,
    name: "Auto Speaker",
    description: "IP67 waterproof",
    price: 59.99,
    stock: 8,
    category: "Audio",
    rating: 4.7,
    image: "",
  },
  {
    id: 5,
    name: "Wireless Spare Part",
    description: "Ergonomic design, silent keys",
    price: 34.99,
    stock: 18,
    category: "Mirrors",
    rating: 4.4,
    image: "",
    badge: { text: "BEST SELLER", type: "best-seller", color: "purple" },
  },
  {
    id: 6,
    name: "RGB Smart LED Bulb",
    description: "16M colors, voice control, scheduling",
    price: 19.99,
    stock: 42,
    category: "smart-home",
    rating: 4.3,
    image: "",
  },
];

export const vendorDetails = {
  name: "Auto Spare Parts Inc.",
  // rating: 0,
  // reviewCount: 0,
  description:
    "Your one-stop shop for all auto spare parts and accessories at competitive prices with premium quality.",
  established: 2015,
  location: "UAE",
  // categories: [],
  email: "contact@afri-trading.com",
  phone: "91+0123466789",
  socialMedia: {
    facebook: "#",
    instagram: "#",
    twitter: "#",
  },
  // verified: true,
  // image: "",
};
